### ISSUE TITLE
instead of plusIntersections, make a single-character intersectionChar argument

### ISSUE THREAD

**Issue by redchair123** [deoxxa/asciitable#5]
Then the default is `intersectionChar:'-'`

**Comment by deoxxa** [comment]
Done!

**Comment by deoxxa** [comment]
I actually really like how this turned out, you can make the table look pretty unique with just this small change.

**Comment by redchair123** [comment]
Remember to push to npm :) 

I'm using this for https://github.com/Niggler/xlsx2tbl

**Comment by deoxxa** [comment]
Already done! :D
